### ISSUE TITLE
Update with NeoVim

### ISSUE THREAD

**Issue by lucasfcosta** [lucasfcosta/dotfiles#7]

**Comment by fatso83** [comment]
I have to say your dotfiles are almost identical to mine in stucture, content and config, except for the zsh part. Even the setup scripts are similar. Funny to poke around. I see I need to add some more vim plugins :-) And of course I added NeoVim like yesterday 🤓

**Comment by lucasfcosta** [comment]
@fatso83 whoa, that's interesting!
I'll take a look at yours later to look for good ideas to incorporate to mine. These ones have been heavily inspired by my friend's [@vieiralucas dotfiles](https://github.com/vieiralucas/dotfiles).
I'm trying to reduce my plugin usage as much as possible to rely on vanilla features whenever they can substitute plugins without making me less productive so I can feel more comfortable on other's environments whenever needed.
